/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40101 SET NAMES binary*/;
INSERT INTO `faqs` VALUES
(1,'Apa itu Hipnoterapi Islami?','Hipnoterapi Islami adalah metode terapi yang menggabungkan teknik hipnoterapi modern dengan nilai-nilai dan prinsip Islam. Terapi ini menggunakan kondisi relaksasi mendalam (trance) untuk mengakses pikiran bawah sadar, dikombinasikan dengan doa, dzikir, dan bimbingan spiritual sesuai syariat Islam.',1,1,'2025-12-25 08:46:27'),
(2,'Apakah Hipnoterapi itu halal?','Ya, hipnoterapi yang dilakukan dengan tujuan menyembuhkan dan membantu seseorang adalah halal. Yang diharamkan adalah hipnosis untuk tujuan hiburan (hypnosis show) atau merugikan orang lain. Di Albashiro, kami memastikan setiap sesi terapi sesuai dengan syariat Islam.',2,1,'2025-12-25 08:46:27'),
(3,'Berapa lama durasi satu sesi terapi?','Durasi satu sesi terapi berkisar antara 90-120 menit, tergantung jenis layanan dan kebutuhan klien. Sesi pertama biasanya lebih lama karena mencakup konsultasi awal dan pengisian form data.',3,1,'2025-12-25 08:46:27'),
(4,'Berapa kali sesi yang dibutuhkan untuk sembuh?','Setiap orang berbeda-beda. Beberapa klien merasakan perubahan signifikan setelah 1-2 sesi, sementara yang lain membutuhkan 3-5 sesi. Terapis akan mendiskusikan rencana terapi yang sesuai dengan kondisi Anda.',4,1,'2025-12-25 08:46:27'),
(5,'Apakah bisa terapi online?','Ya, kami menyediakan layanan terapi online via video call untuk klien yang tidak bisa datang langsung. Efektivitasnya sama dengan terapi offline, asalkan koneksi internet stabil dan berada di ruangan yang tenang.',5,1,'2025-12-25 08:46:27'),
(6,'Apakah rahasia klien terjaga?','Sangat terjaga. Kami menjunjung tinggi kode etik profesi dan menjamin kerahasiaan semua informasi klien. Data dan isi sesi terapi tidak akan dibagikan kepada siapapun tanpa izin klien.',6,1,'2025-12-25 08:46:27'),
(7,'Siapa saja yang bisa menjalani hipnoterapi?','Hipnoterapi aman untuk semua usia, mulai dari anak-anak (minimal 5 tahun) hingga dewasa. Namun, tidak disarankan untuk orang dengan gangguan mental berat (seperti skizofrenia) tanpa rekomendasi dokter.',7,1,'2025-12-25 08:46:27'),
(8,'Bagaimana cara membuat janji?','Anda bisa mengisi form reservasi di website ini atau langsung menghubungi kami via WhatsApp. Setelah itu, tim kami akan mengkonfirmasi jadwal yang tersedia dan memberikan detail lokasi/link meeting.',8,1,'2025-12-25 08:46:27');
